version: "3.4"

services:
  app:
    image: dally-dose
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file: .env
    links:
      - "mongo:mongo"

  mongo:
    image: mongo:latest
    env_file: .env
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./.infra/db:/data/db
