version: "3.4"

services:
  app:
    image: dally-dose
    build:
      context: .
      dockerfile: Dockerfile.dev
    links:
      - "mongo:mongo"
    env_file: .env
    volumes:
      - "./:/usr/src/app"
    ports:
      - 9229:9229
    command: npm run dev -- --inspect=0.0.0.0:9229

  mongo:
    image: mongo:latest
    env_file: .env
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./.infra/db:/data/db

  mongo-express:
    image: mongo-express
    links:
      - "mongo:mongo"
    env_file: .env
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${DB_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${DB_PASSWORD}
